apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-project-backend
  description: Backend service for the AI project
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - backend
    - ai
    - service
spec:
  type: service
  lifecycle: production
  owner: ai-team
  system: ai-project
  providesApis:
    - ai-backend-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ai-backend-api
  description: API provided by the AI backend component
spec:
  type: openapi
  lifecycle: production
  owner: ai-team
  definition: |
    openapi: 3.0.0
    info:
      title: AI Backend API
      version: 1.0.0
    paths:
      /predict:
        post:
          summary: Perform prediction
          responses:
            "200":
              description: Successful prediction

