apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ai-backend-service
  title: AI Backend Service
  description: Template to create an AI backend component with API & TechDocs
  tags:
    - ai
    - backend
    - python
spec:
  owner: ai-team
  type: service

  parameters:
    - title: Provide basic backend information
      required:
        - name
        - owner
      properties:
        name:
          type: string
          title: Name of the backend service name
          description: Unique name of the backend service
          ui:autofocus: true
        description:
          type: string
          title: Description
          description: Describe the service
        owner:
          type: string
          title: Owner
          description: Owner team or group in Backstage
          ui:field: OwnerPicker

    - title: Azure Service Configuration (placeholders only)
      properties:
        azureSubscriptionId:
          type: string
          title: Azure Subscription ID
        resourceGroupName:
          type: string
          title: Resource Group Name
        azureRegion:
          type: string
          title: Azure Region
          default: centralindia
        openaiEndpoint:
          type: string
          title: Azure OpenAI / Foundry Endpoint
        openaiDeployment:
          type: string
          title: Model Deployment Name
        openaiApiVersion:
          type: string
          title: API Version
          default: "2024-05-01-preview"
        cosmosAccountName:
          type: string
          title: Cosmos DB Account Name
        cosmosDatabaseName:
          type: string
          title: Cosmos DB Database Name
        blobStorageAccount:
          type: string
          title: Blob Storage Account Name
        blobContainerName:
          type: string
          title: Blob Container Name
          default: "assets"
        keyVaultName:
          type: string
          title: Key Vault Name
          
    - title: Choose the location
      required:
        - repoUrl
      properties:
        repoUrl:
          type: string
          title: Repository location
          description: Location of the repository, where the repo will be created
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              
  steps:
    - id: fetch
      name: Fetch template skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          # Azure configs to inject into files
          azureSubscriptionId: ${{ parameters.azureSubscriptionId }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          azureRegion: ${{ parameters.azureRegion }}
          openaiEndpoint: ${{ parameters.openaiEndpoint }}
          openaiDeployment: ${{ parameters.openaiDeployment }}
          openaiApiVersion: ${{ parameters.openaiApiVersion }}
          cosmosAccountName: ${{ parameters.cosmosAccountName }}
          cosmosDatabaseName: ${{ parameters.cosmosDatabaseName }}
          blobStorageAccount: ${{ parameters.blobStorageAccount }}
          blobContainerName: ${{ parameters.blobContainerName }}
          keyVaultName: ${{ parameters.keyVaultName }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        description: ${{ parameters.description }}

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open Service in Catalog
        url: ${{ steps.register.output.entityRef }}
      - title: View Repository
        url: ${{ steps.publish.output.remoteUrl }}
